name: Sentence

description: A Flutter app for managing documents and notes.

version: 1.0.0+5

environment:

  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dynamic_color: ^1.6.6
  flutter_launcher_icons: ^0.13.1

  flutter_quill: ^9.3.2

  shared_preferences: ^2.2.2

  image_picker: ^1.0.7

  file_picker: ^6.1.1

  path_provider: ^2.1.3

  permission_handler: ^11.3.1


  animations: ^2.0.11

  flutter:

    sdk: flutter


dev_dependencies:

  flutter_test:

    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

flutter_icons:

  android: true

  ios: false

  image_path: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png" # stavi gde god da ti 
